# Generated by Django 5.1.4 on 2025-06-19 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0009_djangojobexecution_unique_job_executions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'сategory',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг номенклатуры',
                'verbose_name_plural': 'Рейтинг номенклатуры',
                'db_table': 'rating',
                'ordering': ('rating',),
                'default_related_name': '%(model_name)ss',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'review',
                'ordering': ('-created_at',),
                'default_related_name': '%(model_name)ss',
            },
        ),
        migrations.CreateModel(
            name='ProxyDjangoJob',
            fields=[
            ],
            options={
                'verbose_name': 'Задания Django',
                'verbose_name_plural': 'Задания Django',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_apscheduler.djangojob',),
        ),
        migrations.CreateModel(
            name='ProxyDjangoJobExecution',
            fields=[
            ],
            options={
                'verbose_name': 'Выполненное задание Django',
                'verbose_name_plural': 'Выполненные задания Django',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_apscheduler.djangojobexecution',),
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Наименование')),
                ('UID', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('text', models.TextField(max_length=500, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('article', models.CharField(max_length=10, verbose_name='Артикул')),
                ('unit_of_measure', models.CharField(max_length=10, verbose_name='Ед. изм.')),
                ('on_home', models.BooleanField(db_index=True, default=False, verbose_name='На Главной')),
                ('image', models.ImageField(blank=True, upload_to='nomenclature/', verbose_name='Изображение')),
                ('category', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'db_table': 'nomenclature',
                'ordering': ('category',),
                'default_related_name': '%(model_name)ss',
            },
        ),
    ]
