# Generated by Django 5.1.4 on 2025-01-29 20:23

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('UID', models.CharField(editable=False, max_length=36, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('text', models.TextField(max_length=256, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('article', models.CharField(max_length=10, verbose_name='Артикул')),
                ('unit_of_measure', models.CharField(max_length=10, verbose_name='Единица Измерения')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('on_home', models.BooleanField(default=False, verbose_name='На Главной')),
                ('image', models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Dev/kitmetiz/kitm/smedia/nomenclature'), verbose_name='Изображение')),
            ],
            options={
                'ordering': ('category',),
            },
        ),
    ]
