# Generated by Django 5.1.4 on 2025-06-02 21:07

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0009_djangojobexecution_unique_job_executions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('UID', models.CharField(editable=False, max_length=36, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('text', models.TextField(max_length=256, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('article', models.CharField(max_length=10, verbose_name='Артикул')),
                ('unit_of_measure', models.CharField(max_length=10, verbose_name='Ед. изм.')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('on_home', models.BooleanField(default=False, verbose_name='На Главной')),
                ('image', models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Dev/kitmetiz/kitm/smedia/nomenclature'), verbose_name='Изображение')),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='ProxyDjangoJob',
            fields=[
            ],
            options={
                'verbose_name': 'Задания Django',
                'verbose_name_plural': 'Задания Django',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_apscheduler.djangojob',),
        ),
        migrations.CreateModel(
            name='ProxyDjangoJobExecution',
            fields=[
            ],
            options={
                'verbose_name': 'Выполненное задание Django',
                'verbose_name_plural': 'Выполненные задания Django',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_apscheduler.djangojobexecution',),
        ),
    ]
