# Generated by Django 5.1.4 on 2025-06-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='сategory',
        ),
    ]
