# Generated by Django 5.1.4 on 2025-06-15 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='on_home',
            field=models.BooleanField(db_index=True, default=False, verbose_name='На Главной'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
